### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/KMediansPy#3]
Hello,
Great effort on the proposal. I just have some suggestions below,
1- Try to include different distance measures to the first function. As you know many distance measures other than the Euclidean  distance. For example, check this [website ](https://www.datanovia.com/en/lessons/clustering-distance-measures/)
2- Maybe you should include the desired scaling technique as an input to the second function.
3- There are some methods to automatically select the best number of clusters. I suggest you can implement one of these methods in the second function and give the freedom to the user either to let the algorithm to automatically select the number of clusters or input it.
4- In the summary function you can include data summary choices. Such as, tables, charts or both for visualization.

Again, think about these comments as just suggestions not requirements to make your implementation more flexible.

**Comment by aylapear** [comment]
We discussed these suggestions as a group and have made these decisions on each point:
1. We may implement some other distance metrics but at this point already feel like the 3 functions we are creating will take a lot of time to implement
2. For k-medians if people need the data scaled they should do this before
3.  Since there is no "right" number of clusters we feel this should be the choice of the user 
4. For the metrics we are displaying we feel a table is the best output for this function as a chart wouldn't display this type of information well
